# Generated by Django 3.2.7 on 2021-09-14 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
