# Generated by Django 3.2.7 on 2021-09-14 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_orders_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
