# Generated by Django 3.2.7 on 2021-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_orders_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
